# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('trip_app', '0002_auto_20190422_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ManyToManyField(related_name='users', to='login_app.User'),
        ),
    ]
